stages:
  - dockerbuild-push

package:
  image: docker:latest
  stage: dockerbuild-push
  tags: [hanium-runner]
  services:
    - docker:dind
  before_script:
    - docker -v
    - docker login lab.hanium.or.kr -u $GITLAB_USER -p $ACCESS_TOKEN
  script:
    - docker build -t lab.hanium.or.kr/$GITLAB_USER/$PROJECT_NAME .
    - docker push lab.hanium.or.kr:5050/$GITLAB_USER/$PROJECT_NAME