stages:
  - dockerbuild-push

package:
  image: docker:latest
  stage: dockerbuild-push
  tags: [hanium-runner]
  services:
    - docker:dind
  before_script:
    - docker -v
    - docker login lab.hanium.or.kr:5050 -u $DEPLOY_USER -p $DEPLOY_PASSWORD
  script:
    - docker build -t lab.hanium.or.kr:5050/$GITLAB_USER/$PROJECT_NAME .
    - docker push lab.hanium.or.kr:5050/$GITLAB_USER/$PROJECT_NAME